name: Paper draft to PDF

on:
  push:
    branches: 
      - paper

jobs:
  paper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: test
        run: |
          echo "Hello, World!"
          ls
          ls choice_learn/
          ls .github/
          ls .github/actions/

      - name: Build draft PDF
        uses: .github/actions/build-draft
        with:
          journal: joss
          paper-path: docs/paper/paper.md

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          # This is the output path where Pandoc will write the compiled
          # PDF. Note, this should be the same directory as the input
          # paper.md
          path: docs/paper/paper.pdf