name: Build and publish choice-learn

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  publish-service-client-package:
    runs-on: ubuntu-latest
    steps:
      - name: Publish choice-learn on TestPyPI
        uses: ./.github/actions/publish
        with:
          PACKAGE_DIRECTORY: "./choice_learn/"
          PYTHON_VERSION: "3.9"
          PUBLISH_REGISTRY_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
          PUBLISH_REGISTRY_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
          PUBLISH_REGISTRY: "https://test.pypi.org/simple/"
          UPDATE_CODE_VERSION: TEST_PYPI_USERNAME
          PUSH_BRANCH: release_${{ github.event.release.tag_name }}
