name: Build and publish choice-learn on TestPyPI

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  publish-service-client-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish choice-learn on TestPyPI
        uses: ./.github/actions/publish
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE_DIRECTORY: "./choice_learn/"
          PYTHON_VERSION: "3.9"
          PUBLISH_REGISTRY_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
          PUBLISH_REGISTRY_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
          PUBLISH_REGISTRY: "https://test.pypi.org/legacy/"
          UPDATE_CODE_VERSION: true
          PUSH_BRANCH: release_${{ github.event.release.tag_name }}
